version: '3.8'

services:
  nginx:
    image: nginx:1.20.1
    restart: unless-stopped
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    container_name: reverse-proxy
    depends_on:
      - back
      - front


  front:
    build:
      context: ./front
      dockerfile: dev.Dockerfile 
    volumes:
      - ./front:/usr/src/app 
    ports:
      - "3000:3000"
    container_name: FRONT
    depends_on:
      - back


  back:
    build:
      context: ./back
      dockerfile: dev.Dockerfile

    volumes:
      - ./back:/usr/src/app
    
    ports:
      - "3001:3001"
    container_name: BACK
   
